# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeXasNuyNBsiw6lEiP95cS_2jgD_-tQC
"""



import streamlit as st
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the model and TF-IDF vectorizer
model = joblib.load("fake_review_detection.pk1")
vectorizer = joblib.load("tfidf_vectorizer.pk1")  # make sure you save this too

st.title("Fake Review Detector")
st.subheader("Paste a product review to check if it's fake or genuine")

review_input = st.text_area("Enter your review text here")

if st.button("Detect"):
    if not review_input.strip():
        st.warning("Please enter a review.")
    else:
        # Vectorize
        X = vectorizer.transform([review_input])
        prediction = model.predict(X)[0]
        confidence = model.predict_proba(X)[0][prediction]

        label = "FAKE REVIEW" if prediction == 1 else "GENUINE REVIEW"
        st.markdown(f"### Prediction: {label}")
        st.markdown(f"**Confidence:** {confidence*100:.2f}%")